import org.matrix.parallel.*

fun test(){
    val a = MatrixParallel(4,4, false, 150.0)
    val b = MatrixParallel(4,4, false, 150.0)
    var c = AddParallel().add(a, b)
    println(a)
    println()
    println(b)
    println()
    println("Добавление")
    println(c)
    println()
    println("Умножение")
    c = MultParallel().multiply(a, b)
    println(c)
    println()
    println("Скалярное Умножение")
    c = ScalarMultParallel().multiply(a, 5.0)
    println(c)
    println()
    println("Траспонирование")
    c = TransposeParallel().transpose(a)
    println(c)
    println()
    println("Детерминант")
    val det = DeterminantParallel().DetNxNParallel(a)
    println(det)
    println()
}